version: '3.9'

services:
  # MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
    - mongo_db:/data/db

  # Node API service
  api:
    build:
    ports:
      - 4000:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://localhost:27017
      DB_NAME: login-app-db
      NAME: Flora
    depends_on:
    - mongo_db

volumes:
  mongo_db: {}